-- Заполнение данных для Emily Miller (e0dbc5be-c0ee-4ea7-87cb-2c750fe43a94)
-- Deal ID: 022ba431-6c15-483b-bbe2-be70b9d59294

-- 1. Contact Profile
INSERT INTO contact_profiles (
  contact_id,
  first_name,
  last_name,
  email,
  phone,
  lead_status,
  qualification_status,
  summary,
  score,
  nationality,
  residence_country,
  language_primary,
  age_36_50,
  gender_female,
  marital_couple,
  income_gt_100k,
  profession_it,
  timezone
) VALUES (
  'e0dbc5be-c0ee-4ea7-87cb-2c750fe43a94',
  'Emily',
  'Miller',
  'emily.miller@example.com',
  '+34612345678',
  'qualified',
  'hot_lead',
  'Tech professional looking for a sea view property in Marbella area. Budget 300-500k EUR. Ready to view properties.',
  85,
  'British',
  'United Kingdom',
  'English',
  true,
  true,
  true,
  true,
  'Software Engineer',
  'Europe/Madrid'
);

-- 2. Deal Preferences
INSERT INTO deal_preference_profiles (
  deal_id,
  country,
  region,
  city,
  area,
  budget,
  max_budget,
  bedrooms,
  bathrooms,
  type_apartment,
  type_villa,
  loc_coast,
  feature_sea_view,
  feature_pool,
  feature_terrace,
  feature_garage,
  feature_gated_community,
  condition_new_build,
  condition_resale,
  main_home,
  second_home
) VALUES (
  '022ba431-6c15-483b-bbe2-be70b9d59294',
  'Spain',
  'Andalusia',
  'Marbella',
  'Costa del Sol',
  300000,
  500000,
  2,
  2,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  false,
  true
);