-- Migration: Merge deal_preference_profiles columns into deals table
-- This eliminates the need for a separate table and simplifies data persistence.

-- Step 1: Add all columns from deal_preference_profiles to deals
ALTER TABLE public.deals
ADD COLUMN IF NOT EXISTS country text,
ADD COLUMN IF NOT EXISTS region text,
ADD COLUMN IF NOT EXISTS city text,
ADD COLUMN IF NOT EXISTS area text,
ADD COLUMN IF NOT EXISTS loc_coast boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS loc_city_center boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS loc_suburbs boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS loc_rural boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS type_apartment boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS type_villa boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS type_townhouse boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS type_land_plot boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS feature_pool boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS feature_garden boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS feature_terrace boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS feature_garage boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS feature_sea_view boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS feature_mountain_view boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS feature_gated_community boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS condition_new_build boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS condition_resale boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS condition_renovation_ok boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS want_short_term_rental boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS want_long_term_rental boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS dist_beach_lt_1km boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS bedrooms numeric,
ADD COLUMN IF NOT EXISTS bathrooms numeric,
ADD COLUMN IF NOT EXISTS size_sq_m numeric,
ADD COLUMN IF NOT EXISTS budget numeric,
ADD COLUMN IF NOT EXISTS max_budget numeric,
ADD COLUMN IF NOT EXISTS build_type_new boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS build_type_secondhand boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS climate_control_air_conditioning boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS climate_control_central_heating boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS climate_control_fireplace boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS climate_control_ufh_bathrooms boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS climate_control_uf_heating boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS condition_recently_renovated boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS condition_restoration_required boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS feature_access_for_reduced_mobility boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS feature_balcony boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS feature_bar boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS feature_barbeque boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS feature_bar_restaurant boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS feature_basement boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS feature_car_hire_facility boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS feature_children_playground boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS feature_chill_out_area boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS feature_concierge_service boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS feature_courtesy_bus boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS feature_covered_terrace boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS feature_coworking_area boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS feature_dedicated_workspace boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS feature_domotics boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS feature_ensuite_bathroom boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS feature_ev_charger boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS feature_fiber_optic boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS feature_fitted_wardrobes boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS feature_games_room boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS feature_guest_apartment boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS feature_guest_house boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS feature_gym boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS feature_jacuzzi boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS feature_laundry boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS feature_lift boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS feature_marble_flooring boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS feature_near_church boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS feature_near_mosque boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS feature_near_transport boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS feature_outside_gym boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS feature_paddle_tennis boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS feature_padel_court_tennis_court boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS feature_private_parking boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS feature_private_pool boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS feature_restaurant_on_site boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS feature_satellite_tv boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS feature_sauna boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS feature_solarium boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS feature_spa boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS feature_stables boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS feature_staff_accommodation boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS feature_storage_room boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS feature_utility_room boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS feature_yoga_area boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS furniture_fully_furnished boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS furniture_not_furnished boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS duplex boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS kitchen_fully_fitted boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS kitchen_kitchen_lounge boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS kitchen_partially_fitted boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS location_type_beachfront boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS location_type_beachside boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS location_type_close_to_forest boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS location_type_close_to_golf boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS location_type_close_to_marina boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS location_type_close_to_port boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS location_type_close_to_schools boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS location_type_close_to_sea boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS location_type_close_to_shops boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS location_type_close_to_town boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS location_type_country boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS location_type_front_line_beach_complex boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS location_type_frontline_golf boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS location_type_marina boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS location_type_mountain_pueblo boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS location_type_port boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS location_type_suburban boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS location_type_town boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS location_type_urbanisation boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS location_type_village boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS parking_gated boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS parking_private boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS parking_underground boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS pool_childrens_pool boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS pool_communal boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS pool_heated boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS pool_indoor boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS pool_private boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS security_24_hour_security boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS security_electric_blinds boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS security_gated_complex boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS subtype_duplex boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS subtype_finca_cortijo boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS subtype_ground_floor_apartment boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS subtype_ground_floor_studio boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS subtype_middle_floor_apartment boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS subtype_middle_floor_studio boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS subtype_mobile_home boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS subtype_penthouse boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS subtype_penthouse_duplex boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS subtype_semi_detached_house boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS subtype_top_floor_apartment boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS subtype_top_floor_studio boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS subtype_detached_villa boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS view_beach boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS view_country boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS view_courtyard boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS view_forest boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS view_garden boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS view_golf boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS view_lake boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS view_mountain boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS view_panoramic boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS view_pool boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS view_port boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS view_sea boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS view_street boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS view_urban boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS main_home boolean,
ADD COLUMN IF NOT EXISTS second_home boolean,
ADD COLUMN IF NOT EXISTS timeline text,
ADD COLUMN IF NOT EXISTS location_ids integer[],
ADD COLUMN IF NOT EXISTS feature_ids text[],
-- Additional columns from extract-lead-details schema
ADD COLUMN IF NOT EXISTS dist_golf_lt_2km boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS group_subtype_apartment boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS group_subtype_detached boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS group_subtype_duplex boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS group_subtype_townhouse boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS condition_recently_refurbished boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS condition_excellent boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS completion_type_construction boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS completion_type_ready boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS fireplace boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS parking_covered boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS parking_garage boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS security_alarm_system boolean DEFAULT false;

-- Step 2: Migrate existing data from deal_preference_profiles to deals
UPDATE public.deals d SET
    country = dpp.country,
    region = dpp.region,
    city = dpp.city,
    area = dpp.area,
    loc_coast = dpp.loc_coast,
    loc_city_center = dpp.loc_city_center,
    loc_suburbs = dpp.loc_suburbs,
    loc_rural = dpp.loc_rural,
    type_apartment = dpp.type_apartment,
    type_villa = dpp.type_villa,
    type_townhouse = dpp.type_townhouse,
    type_land_plot = dpp.type_land_plot,
    feature_pool = dpp.feature_pool,
    feature_garden = dpp.feature_garden,
    feature_terrace = dpp.feature_terrace,
    feature_garage = dpp.feature_garage,
    feature_sea_view = dpp.feature_sea_view,
    feature_mountain_view = dpp.feature_mountain_view,
    feature_gated_community = dpp.feature_gated_community,
    condition_new_build = dpp.condition_new_build,
    condition_resale = dpp.condition_resale,
    condition_renovation_ok = dpp.condition_renovation_ok,
    want_short_term_rental = dpp.want_short_term_rental,
    want_long_term_rental = dpp.want_long_term_rental,
    dist_beach_lt_1km = dpp.dist_beach_lt_1km,
    bedrooms = dpp.bedrooms,
    bathrooms = dpp.bathrooms,
    size_sq_m = dpp.size_sq_m,
    budget = dpp.budget,
    max_budget = dpp.max_budget,
    build_type_new = dpp.build_type_new,
    build_type_secondhand = dpp.build_type_secondhand,
    climate_control_air_conditioning = dpp.climate_control_air_conditioning,
    condition_recently_renovated = dpp.condition_recently_renovated,
    feature_access_for_reduced_mobility = dpp.feature_access_for_reduced_mobility,
    feature_balcony = dpp.feature_balcony,
    feature_barbeque = dpp.feature_barbeque,
    feature_bar_restaurant = dpp.feature_bar_restaurant,
    feature_basement = dpp.feature_basement,
    feature_children_playground = dpp.feature_children_playground,
    feature_concierge_service = dpp.feature_concierge_service,
    feature_courtesy_bus = dpp.feature_courtesy_bus,
    feature_covered_terrace = dpp.feature_covered_terrace,
    feature_coworking_area = dpp.feature_coworking_area,
    feature_dedicated_workspace = dpp.feature_dedicated_workspace,
    feature_domotics = dpp.feature_domotics,
    feature_ensuite_bathroom = dpp.feature_ensuite_bathroom,
    feature_ev_charger = dpp.feature_ev_charger,
    feature_fitted_wardrobes = dpp.feature_fitted_wardrobes,
    feature_guest_house = dpp.feature_guest_house,
    feature_gym = dpp.feature_gym,
    feature_jacuzzi = dpp.feature_jacuzzi,
    feature_lift = dpp.feature_lift,
    feature_marble_flooring = dpp.feature_marble_flooring,
    feature_padel_court_tennis_court = dpp.feature_padel_court_tennis_court,
    feature_private_parking = dpp.feature_private_parking,
    feature_private_pool = dpp.feature_private_pool,
    feature_sauna = dpp.feature_sauna,
    feature_solarium = dpp.feature_solarium,
    feature_spa = dpp.feature_spa,
    feature_storage_room = dpp.feature_storage_room,
    location_type_beachside = dpp.location_type_beachside,
    location_type_close_to_forest = dpp.location_type_close_to_forest,
    location_type_close_to_golf = dpp.location_type_close_to_golf,
    location_type_close_to_marina = dpp.location_type_close_to_marina,
    location_type_close_to_schools = dpp.location_type_close_to_schools,
    location_type_close_to_sea = dpp.location_type_close_to_sea,
    location_type_close_to_town = dpp.location_type_close_to_town,
    location_type_country = dpp.location_type_country,
    location_type_suburban = dpp.location_type_suburban,
    location_type_town = dpp.location_type_town,
    location_type_urbanisation = dpp.location_type_urbanisation,
    parking_gated = dpp.parking_gated,
    parking_underground = dpp.parking_underground,
    pool_childrens_pool = dpp.pool_childrens_pool,
    pool_communal = dpp.pool_communal,
    pool_heated = dpp.pool_heated,
    pool_indoor = dpp.pool_indoor,
    pool_private = dpp.pool_private,
    security_24_hour_security = dpp.security_24_hour_security,
    security_electric_blinds = dpp.security_electric_blinds,
    security_gated_complex = dpp.security_gated_complex,
    subtype_duplex = dpp.subtype_duplex,
    subtype_finca_cortijo = dpp.subtype_finca_cortijo,
    subtype_ground_floor_apartment = dpp.subtype_ground_floor_apartment,
    subtype_ground_floor_studio = dpp.subtype_ground_floor_studio,
    subtype_middle_floor_apartment = dpp.subtype_middle_floor_apartment,
    subtype_middle_floor_studio = dpp.subtype_middle_floor_studio,
    subtype_penthouse = dpp.subtype_penthouse,
    subtype_top_floor_apartment = dpp.subtype_top_floor_apartment,
    subtype_top_floor_studio = dpp.subtype_top_floor_studio,
    main_home = dpp.main_home,
    second_home = dpp.second_home,
    timeline = dpp.timeline,
    location_ids = dpp.location_ids,
    feature_ids = dpp.feature_ids
FROM public.deal_preference_profiles dpp
WHERE d.id = dpp.deal_id;

-- Step 3: Drop the old table 
DROP TABLE IF EXISTS public.deal_preference_profiles CASCADE;

-- Done!
